{% set version = "0.8.0" %}

package:
  name: mapio
  version: {{ version }}

source:
  url: https://github.com/usgs/MapIO/archive/{{ version }}.tar.gz
  sha256: 2f08d66b8647b53f08aa0f89de6d9c09a5ff8a57b6de7ff3cc5b4108410e373e

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - gdal
    - h5py
    - matplotlib
    - netcdf4
    - pandas
    - rasterio
    - scipy
    - shapely

test:

  imports:
    - mapio

about:
  home: https://github.com/usgs/MapIO
  license: Public Domain
  summary: USGS library for dealing with gridded data (loading, interpolation, etc.)
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
