{% set version = "0.7.27" %}

package:
  name: mapio
  version: {{ version }}

source:
  url: https://github.com/usgs/MapIO/archive/{{ version }}.tar.gz
  sha256: 4b2f0ad4d701a2f50daa500b691436ae96864be46bc35d5db18508d192240f9b

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - gdal
    - h5py
    - matplotlib
    - netcdf4
    - pandas
    - rasterio
    - scipy
    - shapely

test:

  imports:
    - mapio

about:
  home: https://github.com/usgs/MapIO
  license: Public Domain
  summary: USGS library for dealing with gridded data (loading, interpolation, etc.)
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
