travis:
  secure:
    BINSTAR_TOKEN: bjVZKdMYk6eUd/L35q8r8Nv6TWX+PZ+zW6rXB2kUYMxDQG6tvQ42HaInWu2mp9RZ4imWTCAfI4LBhl0A/M6TUA9KyFd/qyShlcvDyq3mWutg43rGxffGr7FQV6q3a0taMmySbCpZSNB4gPwUomRa2ygi/d7HRTYRtG9FkJnISzP6E9qwIkZ1D2piP7n57RRj9hPNzVHJgKGTzPzTGxaTMtl3puTG1DRBuVSGCIAzmM4/9ubX+h9I4higpbVRHT+c4XG6U0uCGC22qDRZ1kbpYToR4Hp0BQgT2Lj4jr0yK7Edi3OeoQ+YjLXRWd/9tG+hJ3ybZDOXVN1bSkOSxu9hmAokOerIVPAc+DbwwkLjqwqPt+3X3h/oWDR+3+ckkJlNbFHZ9o+FR3r9dIDMUZXPllSNa6tx1qZaTlC4BRY6GWpWtc2IdebD42IofU102qvcVVPNPz+9E+4cYgh3SiNefqCnmmi/tlc1IbdJcvnUy84JPkdtO9ERY2jW2uUjuYtmZvPLKR8lGQBPXSHxRW89Qvzw24l+PE34+cxsdoxSecUv8SYwUyWmVg3+pKgpUMX8nmrQl2ODczhTFQY67vVANJM7Ozn7ixIaLckVxcXYjkRfoyGSBPv+DOdt4hIzfIG89l+kIgb7oTT/H6PPSnChjf61zBqEJbZ6/cwTKC9DpCk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
